{% set name = "survindel2" %}
{% set version = "1.1.3" %}

package:
  name: {{ name|lower }}
  version: {{ version }}

source:
  url: https://github.com/kensung-lab/SurVIndel2/archive/refs/tags/{{ version }}.tar.gz
  sha256: 02a91122e1c0fc87794c480504ea2c3ee64f5f54f3a6ee606c07aa20ec3fc38d

build:
  number: 0

requirements:
  build:
    - {{ compiler('cxx') }}
  host:
    - htslib >=1.13
  run:
    - pysam >=0.16.0.1
    - pyfaidx >=0.5.9.1
    - numpy
    - scikit-learn>=1.2.2

test:
  source_files:
    - demo/reads.bam
    - demo/reads.bam.bai
    - demo/ref.fa
    - demo/ref.fa.fai

  requires:
    - bcftools

about:
  home: https://github.com/kensung-lab/SurVIndel2
  summary: 'A CNV caller for Illumina paired-end WGS data.'
  description: |
    SurVIndel2 is a fast and accurate CNV caller for Illumina paired-end WGS data.
  license: GPL-3.0-only
  license_file: LICENSE

extra:
  recipe-maintainers:
    - Mesh89
